spring:
  application:
    name: read
#  profiles:
#    active: ${cloud.profiles.active:local}
server:
  port: 10000
# 日志输出配置
logging:
  level:
    live:
      xiaoxu:
        DEBUG
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  check-config-location: true
  configuration:
    # Mybatis 二级缓存
    cache-enabled: false
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 这个配置会将执行的 sql 打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
  global-config:
    #    db-config:
    # 主键类型
    #      id-type: assign_id
    # 展示 banner
    banner: false