spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_encryption?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: your_custom_password