spring:
  application:
    name: read-write-separation
  profiles:
    active: ${cloud.profiles.active:local}
server:
  port: 10000
# 日志输出配置
logging:
  level:
    live:
      xiaoxu:
        DEBUG
  # 日志输出配置
  #    root: TRACE
  config: logback-spring.xml