spring:
  application:
    name: read-write-separation
  profiles:
    active: ${cloud.profiles.active:local}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 10000
# 日志输出配置
logging:
  level:
    live:
      xiaoxu:
        DEBUG